"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const React = require("react");
class LayoutView extends React.Component {
    render() {
        return React.createElement("div", { className: "home-page" },
            React.createElement("div", { className: "banner" },
                React.createElement("div", { className: "container" },
                    React.createElement("h1", { className: "logo-font" }, "conduit"),
                    React.createElement("p", null, "A place to share your knowledge."))),
            React.createElement("div", { className: "container page" },
                React.createElement("div", { className: "row" },
                    React.createElement("div", { className: "col-md-9" },
                        React.createElement("div", { className: "feed-toggle" },
                            React.createElement("ul", { className: "nav nav-pills outline-active" },
                                React.createElement("li", { className: "nav-item" },
                                    React.createElement("a", { className: "nav-link disabled", href: "" }, "Your Feed")),
                                React.createElement("li", { className: "nav-item" },
                                    React.createElement("a", { className: "nav-link active", href: "" }, "Global Feed")))),
                        React.createElement("div", { className: "article-preview" },
                            React.createElement("div", { className: "article-meta" },
                                React.createElement("a", { href: "profile.html" },
                                    React.createElement("img", { src: "http://i.imgur.com/Qr71crq.jpg" })),
                                React.createElement("div", { className: "info" },
                                    React.createElement("a", { href: "", className: "author" }, "Eric Simons"),
                                    React.createElement("span", { className: "date" }, "January 20th")),
                                React.createElement("button", { className: "btn btn-outline-primary btn-sm pull-xs-right" },
                                    React.createElement("i", { className: "ion-heart" }),
                                    " 29")),
                            React.createElement("a", { href: "", className: "preview-link" },
                                React.createElement("h1", null, "How to build webapps that scale"),
                                React.createElement("p", null, "This is the description for the post."),
                                React.createElement("span", null, "Read more..."))),
                        React.createElement("div", { className: "article-preview" },
                            React.createElement("div", { className: "article-meta" },
                                React.createElement("a", { href: "profile.html" },
                                    React.createElement("img", { src: "http://i.imgur.com/N4VcUeJ.jpg" })),
                                React.createElement("div", { className: "info" },
                                    React.createElement("a", { href: "", className: "author" }, "Albert Pai"),
                                    React.createElement("span", { className: "date" }, "January 20th")),
                                React.createElement("button", { className: "btn btn-outline-primary btn-sm pull-xs-right" },
                                    React.createElement("i", { className: "ion-heart" }),
                                    " 32")),
                            React.createElement("a", { href: "", className: "preview-link" },
                                React.createElement("h1", null, "The song you won't ever stop singing. No matter how hard you try."),
                                React.createElement("p", null, "This is the description for the post."),
                                React.createElement("span", null, "Read more...")))),
                    React.createElement("div", { className: "col-md-3" },
                        React.createElement("div", { className: "sidebar" },
                            React.createElement("p", null, "Popular Tags"),
                            React.createElement("div", { className: "tag-list" }, this.props.data.tags.map((tag) => React.createElement("a", { key: tag, href: "", className: "tag-pill tag-default" }, tag))))))));
    }
}
exports.default = LayoutView;
